import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const repoRoot = path.resolve(import.meta.dirname, "..");
const wrapperScript = path.join(repoRoot, "scripts", "codex_with_traffic_light.sh");
const codexDir = path.join(os.homedir(), ".codex");
const integrationPath = path.join(codexDir, "codex-traffic-light.zsh");
const zshrcPath = path.join(os.homedir(), ".zshrc");
const startMarker = "# >>> codex traffic light";
const endMarker = "# <<< codex traffic light";

function findDefaultCodexBinary() {
  const candidates = [
    process.env.CODEX_BIN,
    "/Applications/Codex.app/Contents/Resources/codex",
    "/opt/homebrew/bin/codex",
    "/usr/local/bin/codex"
  ].filter(Boolean);

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      return candidate;
    }
  }
  return "codex";
}

function shellQuote(value) {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function replaceMarkedBlock(text, block) {
  const escapedStart = startMarker.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const escapedEnd = endMarker.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const pattern = new RegExp(
    `${escapedStart}[\\s\\S]*?${escapedEnd}\\n?`,
    "m"
  );
  if (pattern.test(text)) {
    text = text.replace(pattern, "");
  }
  if (hasUnterminatedHeredoc(text)) {
    const suffix = text.length === 0 || text.startsWith("\n") ? text : `\n${text}`;
    return `${block}\n${suffix}`;
  }
  const prefix = text.endsWith("\n") || text.length === 0 ? text : `${text}\n`;
  return `${prefix}\n${block}\n`;
}

function hasUnterminatedHeredoc(text) {
  let terminator = null;
  for (const line of text.split(/\r?\n/)) {
    if (terminator) {
      if (line.trim() === terminator) {
        terminator = null;
      }
      continue;
    }

    const match = line.match(/<<-?\s*["']?([A-Za-z_][A-Za-z0-9_]*)["']?\s*$/);
    if (match) {
      terminator = match[1];
    }
  }
  return Boolean(terminator);
}

if (!fs.existsSync(wrapperScript)) {
  throw new Error(`Missing wrapper script: ${wrapperScript}`);
}

fs.mkdirSync(codexDir, { recursive: true });

const integration = `# Codex traffic light Terminal integration.
# Generated by install_codex_terminal_integration.mjs.
# Source this file from ~/.zshrc to wrap the codex CLI command.

_codex_traffic_light_wrapper=${shellQuote(wrapperScript)}
_codex_traffic_light_codex_bin=${shellQuote(findDefaultCodexBinary())}

_codex_traffic_light_run_codex() {
  if [[ "$_codex_traffic_light_codex_bin" == */* ]]; then
    "$_codex_traffic_light_codex_bin" "$@"
  else
    command "$_codex_traffic_light_codex_bin" "$@"
  fi
}

codex() {
  _codex_traffic_light_codex_bin="\${CODEX_BIN:-$_codex_traffic_light_codex_bin}"

  if [ "\${CODEX_TRAFFIC_LIGHT_DISABLE:-}" = "1" ]; then
    _codex_traffic_light_run_codex "$@"
    return $?
  fi

  if [ -x "$_codex_traffic_light_wrapper" ]; then
    CODEX_BIN="$_codex_traffic_light_codex_bin" "$_codex_traffic_light_wrapper" "$@"
    return $?
  fi

  printf '%s\\n' "Codex traffic light wrapper is missing: $_codex_traffic_light_wrapper" >&2
  _codex_traffic_light_run_codex "$@"
}
`;

fs.writeFileSync(integrationPath, integration);

let zshrc = fs.existsSync(zshrcPath) ? fs.readFileSync(zshrcPath, "utf8") : "";
if (zshrc && !fs.existsSync(`${zshrcPath}.codex-traffic-light.bak`)) {
  fs.writeFileSync(`${zshrcPath}.codex-traffic-light.bak`, zshrc);
}

const block = `${startMarker}\nsource ${shellQuote(integrationPath)}\n${endMarker}`;
zshrc = replaceMarkedBlock(zshrc, block);
fs.writeFileSync(zshrcPath, zshrc.endsWith("\n") ? zshrc : `${zshrc}\n`);

console.log(`Wrote ${integrationPath}`);
console.log(`Updated ${zshrcPath}`);
console.log("Restart Terminal, or run: source ~/.zshrc");
